lr: 3e-4
beta: 0.9
beta1: 0.9
beta2: 0.99
beta3: 0.99999
eps: 0.0001
batch_size: 512
epochs: 200
ministeps: 1 #number of steps to do on a particular minibatch before moving to next one
wd: 0.0
scale_type: random
log_differences: true
warmup_examples: 128000
debias: true
optimizer: ???
dataset: c4
valid_frequency_examples: 128000000
context_length: 1024
valid_examples: 102400000
num_workers: 8
logging: True
wandb_project: learnedlr