train:
  optimizer: pertensor_randomol
  ol: ptscaleadamw
  scale_type: random
  epsilon: 1e-8

  expmd_min: 1e-10
  expmd_max: 1e-2

  warmup_examples: 5120
  lr: 1.0
  beta1: 0.9
  beta2: 0.99
  batch_size: 512
  valid_frequency_examples: 409600
  valid_examples: 102400

  num_workers: 4

  log_differences: true
  logging: true
  wandb_project: learnedlrC4
  log_interval: 50